### ISSUE TITLE
Rename cronjob from delete-es-job to purge-es-job

### ISSUE THREAD

**Issue by d3c3mber** [alipay/container-observability-service#121]
### There's no existing/similar bug report.

- [X] I have searched the existing issues

### Describe the bug:

Rename the cronjob as delete is not a proper word

### Expected behavior:

N/A

**Comment by ponsAoki** [comment]
@d3c3mber 
Nice to meet you!
I am thinking of creating a Pull Request to resolve this issue.
Can you tell me how to sign the CLA?

**Comment by d3c3mber** [comment]
Hi @ponsAoki, thanks very much for reaching out. 
Please free feel to open an PR for this issue. For lunettes, we don't request a CLA, we are using [DCO (Developer Certificate of Origin)](https://developercertificate.org/) ,  contributors are required to sign off that they adhere to those requirements by adding a Signed-off-by line to the commit messages. Git has provided a -s command line option to append that automatically to your commit messages, please use it when you commit your changes.
$ git commit -s -m 'This is my commit message'
