### ISSUE TITLE
change QUICK_START.md filename to quick_start.md

### ISSUE THREAD

**Issue by larryck** [alipay/container-observability-service#31]
### There's no existing/similar bug report.

- [X] I have searched the existing issues

### Describe the bug:

The filename QUICK_START.md  is confusing to users, it'd be better to change it to lowercase letters.

### Expected behavior:

change QUICK_START.md filename to quick_start.md

**Comment by larryck** [comment]
@hnhbwlp @d3c3mber  What do you think ?

**Comment by d3c3mber** [comment]
LGTM

**Comment by larryck** [comment]
Close because it's fixed by #32
