### ISSUE TITLE
Install failed through helm

### ISSUE THREAD

**Issue by zwForrest** [alipay/container-observability-service#59]
### There's no existing/similar bug report.

- [X] I have searched the existing issues

### Describe the bug:

The deployment failed through Helm, and several components cannot run properly.

### Expected behavior:

Helm can deploy and run the corresponding components properly. For example, for components that require a password, a default password can be configured, and for components that do not have sufficient permissions, the corresponding rbac needs to be configured.

### Lunettes version

main

### Kubernetes version

v1.21.3

**Comment by linuzb** [comment]
@zwForrest Please show more details, such as component logs.

**Comment by zwForrest** [comment]
> @zwForrest Please show more details, such as component logs.

1. The grafanadi pod requires configmap permissions.
2. jaeger pod  logs `{"level":"info","ts":1701216267.1549637,"caller":"grpc@v1.54.0/server.go:935","msg":"[core][Server #2] grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams failed to receive the preface from client: unexpected EOF\"","system":"grpc","grpc_log":true}`.
3. Also, where can I find how the Prometheus expressions in your articles are aggregated?

**Comment by larryck** [comment]
> > @zwForrest Please show more details, such as component logs.
> 
> 1. The grafanadi pod requires configmap permissions.
> 2. jaeger pod  logs `{"level":"info","ts":1701216267.1549637,"caller":"grpc@v1.54.0/server.go:935","msg":"[core][Server #2] grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams failed to receive the preface from client: unexpected EOF\"","system":"grpc","grpc_log":true}`.
> 3. Also, where can I find how the Prometheus expressions in your articles are aggregated?

thanks @zwForrest . Cloud you give some context of your Kubernetes cluster? Is it a pre-built cluster? If not, which bootstrap tool have you used to create the cluster? And also, which tenant you used to deploy lunettes?

**Comment by zwForrest** [comment]
@larryck This is an existing k8s cluster created by kubeadm. I deployed lunettes by helm.

**Comment by zwForrest** [comment]
Is there a DingTalk groups available？
